- name: Example tags
  hosts: all

  tasks:
    - name: Task 1
      debug:
        msg: "This is Task 1"
      tags:
        - tag1

    - name: Task 2
      debug:
        msg: "This is Task 2"
      tags:
        - tag2
